.PHONY: clean All

All:
	@echo "----------Building project:[ hello_world - Debug ]----------"
	@"$(MAKE)" -f  "hello_world.mk"
clean:
	@echo "----------Cleaning project:[ hello_world - Debug ]----------"
	@"$(MAKE)" -f  "hello_world.mk" clean
