.PHONY: clean All

All:
	@echo "----------Building project:[ p3-1 - Debug ]----------"
	@"$(MAKE)" -f  "p3-1.mk"
clean:
	@echo "----------Cleaning project:[ p3-1 - Debug ]----------"
	@"$(MAKE)" -f  "p3-1.mk" clean
